### ISSUE TITLE
Ouvrir automatiquement la page du jour

### ISSUE THREAD

**Issue by NathanBnm** [Skyost/UnicaenTimetable#10]
Depuis la dernière mise à jour (version 2.2.5) la page du jour ne se charge plus automatiquement en ouvrant l'application.

Je ne suis pas le seul à avoir ce problème.

Pourtant l'option est bien activée dans les paramètres.

Edit : J'ai désinstallé et réinstallé l'application mais celà n'a rien changé.

**Comment by Skyost** [comment]
Je vais investiguer sur ce problème.

**Comment by Skyost** [comment]
Corrigé, merci beaucoup !
