### ISSUE TITLE
[Amélioration] Gestion ergonomique des semaines

### ISSUE THREAD

**Issue by Funtrac** [Skyost/UnicaenTimetable#2]
Constat : ce n'est pas très rapide de cliquer sur changer la semaine pour passer à la semaine suivante et de cliquer sur une flèche pour changer de jour

Proposition : Utiliser un swip screen de l'utilisateur pour changer de jour et passer automatiquement à la semaine suivante lorsque qu'un utilisateur swippe vers la gauche un vendredi.

**Comment by Skyost** [comment]
Je suis d'accord. Je pense laisser le sélecteur de semaine mais également ajouter la possibilité de swipper sur une autre semaine (si celle-ci a été téléchargée).
