### ISSUE TITLE
Information caché / qui ne s'affiche pas

### ISSUE THREAD

**Issue by Manerr** [Skyost/UnicaenTimetable#7]
Depuis la dernière mise à jour, certains cours sont moins détaillés ou l'information est tronquée et même certains cours ne s'affichent plus du tout.

![Screenshot_2019-03-16-22-28-59-816_fr skyost timetable](https://user-images.githubusercontent.com/1338257/54482064-e7c28280-483d-11e9-9441-3f56c088505f.png)

**Comment by Skyost** [comment]
En fait j'ai mis à jour la librairie qui permet d'afficher des calendriers sur une journée (librairie que j'avais d'ailleurs eu à tweaker un peu pour afficher toutes les infos comme il le faut).

Je vais essayer de corriger ça dans la journée.
