### ISSUE TITLE
Widget

### ISSUE THREAD

**Issue by Manerr** [Skyost/UnicaenTimetable#8]
Le widget indiquant l'emploi du temps omet certains cours ou certains cours sont mal placés (les horaires ne s'enchaînent pas) 
(Sur l'exemple, j'ai cours de 8h à 10h, ce cours s'affiche dans l'application mais pas dans le widget) 
![Screenshot_2019-03-18-07-54-48-497_com miui home](https://user-images.githubusercontent.com/1338257/54512166-9ad0d000-4953-11e9-9bfc-6127d36cb407.png)
![Screenshot_2019-03-18-07-55-12-847_com miui home](https://user-images.githubusercontent.com/1338257/54512176-a15f4780-4953-11e9-9c0d-5421e9622312.png)

**Comment by Skyost** [comment]
Oulah effectivement ! Possibilité d'avoir un screen du jour en question dans l'appli ?

**Comment by Manerr** [comment]
![Screenshot_2019-03-18-14-43-13-097_fr skyost timetable](https://user-images.githubusercontent.com/1338257/54534231-37af5f80-498c-11e9-90a3-9f8e956a02ee.png)
![Screenshot_2019-03-18-14-43-16-078_fr skyost timetable](https://user-images.githubusercontent.com/1338257/54534244-3d0caa00-498c-11e9-9765-7c40fe943e97.png)

**Comment by NathanBnm** [comment]
J'ai rencontré le même problème j'avais fait une capture d'écran aussi mais j'ai pas eu le temps de le signaler plus vite :smile:

![image](https://user-images.githubusercontent.com/45366162/54638714-f900ce80-4a8b-11e9-9d6b-afe53d0b8dce.png)

**Comment by Skyost** [comment]
Merci beaucoup à vous deux, je regarderai ça dans la soirée ! :wink:

**Comment by Skyost** [comment]
Je pense avoir corrigé l'erreur, j'envoie une mise à jour qui se déploiera dans la nuit. Si vous le pouvez, essayez de la télécharger demain matin et dîtes-moi en des nouvelles :wink:

**Comment by NathanBnm** [comment]
C'est bien corrigé 😉

**Comment by Skyost** [comment]
Magnifique !
