### ISSUE TITLE
Apparence

### ISSUE THREAD

**Issue by NathanBnm** [Skyost/UnicaenTimetable#9]
Par simple curiosité, je ne ne sais pas si c'est normal où si c'est un bug, mais pourquoi certains dans leur application ont le nom des cours en gras et la barre horizontale qui indique l'horaire comme sur Zimbra, et d'autres non ? Je ne les ai pas par exemple. C'est en lien avec la version d'Android ?

**Comment by Skyost** [comment]
Serait-il possible d'avoir une capture d'écran du problème en question ?

**Comment by NathanBnm** [comment]
Ah oui je comprend. Cela y était dans les anciennes versions ? Je dois avoir des amis qui ne doivent pas avoir fait les mises à jour alors. Je peux envoyer mon rendu, mais pas l'autre rendu pour le moment. Je vais voir si je peux avoir ça demain.

Sinon oui effectivement ce serait intéressant :+1:

**Comment by NathanBnm** [comment]
![image](https://user-images.githubusercontent.com/45366162/54638672-dd95c380-4a8b-11e9-836f-b6d50b74c509.png)

**Comment by Skyost** [comment]
Ça marche, je pense voir ce que tu veux dire !

**Comment by Skyost** [comment]
![Screenshot_1553026685](https://user-images.githubusercontent.com/3882599/54638945-85ab8c80-4a8c-11e9-9de5-5ca158b21d21.png)

Et voilà le travail :wink:    
La barre verticale a également été ajoutée !

**Comment by NathanBnm** [comment]
Et oui voilà c'est bien ça ! :+1:
